name: Release Build

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-firmware:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - uses: alire-project/setup-alire@b607671067a8ca5d7b7f4a12dadb4dc009cd2cc7

    - run: >
        sudo apt-get install -y python3-dev libffi-dev build-essential libncurses-dev gcc-arm-none-eabi binutils-arm-none-eabi libusb-1.0 &&
        make -C kalico &&
        bash -c 'cd firmware/board_support/bb-runtimes/ && ./runtimes.sh' &&
        make firmware/bin/prunt_board_3_firmware_with_crc.bin

    - uses: actions/upload-artifact@v4
      with:
        name: prunt_board_3_firmware_with_crc.bin
        path: firmware/bin/prunt_board_3_firmware_with_crc.bin

    - uses: actions/upload-artifact@v4
      with:
        name: prunt_board_3_firmware.elf
        path: firmware/bin/prunt_board_3_firmware.elf

  build-linux-x64-server:
    runs-on: ubuntu-latest

    needs: build-firmware

    steps:
    - uses: actions/checkout@v4

    - uses: alire-project/setup-alire@b607671067a8ca5d7b7f4a12dadb4dc009cd2cc7

    - uses: actions/download-artifact@v4
      with:
        name: prunt_board_3_firmware_with_crc.bin
        path: server/embedded_resources

    - run: >
        sudo apt-get install -y libudev-dev &&
        cd server &&
        alr install are &&
        PATH=$PATH:$HOME/.alire/bin make -C embedded_resources &&
        alr build --release &&
        mv bin/prunt_board_3_server bin/prunt_board_3_server_linux_x64_release
        # alr clean &&
        # alr build --development &&
        # mv bin/prunt_board_3_server bin/prunt_board_3_server_linux_x64_debug

    # - uses: actions/upload-artifact@v4
    #   with:
    #     name: prunt_board_3_server_linux_x64_debug
    #     path: server/bin/prunt_board_3_server_linux_x64_debug

    - uses: actions/upload-artifact@v4
      with:
        name: prunt_board_3_server_linux_x64_release
        path: server/bin/prunt_board_3_server_linux_x64_release

  build-linux-aarch64-server:
    runs-on: raspberry-pi-5

    needs: build-firmware

    steps:
    - uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        name: prunt_board_3_firmware_with_crc.bin
        path: server/embedded_resources

    - run: >
        sudo apt-get install -y libudev-dev &&
        cd server &&
        PATH=$PATH:$HOME/.alire/bin make -C embedded_resources &&
        alr build --release &&
        mv bin/prunt_board_3_server bin/prunt_board_3_server_linux_aarch64_release
        # alr clean &&
        # alr build --development &&
        # mv bin/prunt_board_3_server bin/prunt_board_3_server_linux_aarch64_debug

    # - uses: actions/upload-artifact@v4
    #   with:
    #     name: prunt_board_3_server_linux_aarch64_debug
    #     path: server/bin/prunt_board_3_server_linux_aarch64_debug

    - uses: actions/upload-artifact@v4
      with:
        name: prunt_board_3_server_linux_aarch64_release
        path: server/bin/prunt_board_3_server_linux_aarch64_release

  release:
    runs-on: ubuntu-latest

    needs:
    - build-firmware
    - build-linux-aarch64-server
    - build-linux-x64-server

    permissions:
      contents: write

    steps:
    - uses: actions/download-artifact@v4

    - uses: softprops/action-gh-release@01570a1f39cb168c169c802c3bceb9e93fb10974
      with:
        files: |
          prunt_board_3_server_linux_x64_release/prunt_board_3_server_linux_x64_release
          prunt_board_3_server_linux_aarch64_release/prunt_board_3_server_linux_aarch64_release
        fail_on_unmatched_files: true
        draft: true
